### ISSUE TITLE
Descrizione

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/cifre#1]
![es2_30](https://cloud.githubusercontent.com/assets/3002194/15364985/cf775964-1d1e-11e6-8833-fe722b14fe23.jpg)

**Comment by luca998** [comment]
Una mano?

**Comment by FabioZTessitore** [comment]
haha ma dai. Comincia a fare un programma che chiede l'input di un numero e se non è a cinque cifre stampa un messaggio di errore ed esce

poi vediamo se riesci ad estrarre qualche cifra dal numero

**Comment by luca998** [comment]
il ritorno hahah

**Comment by FabioZTessitore** [comment]
bentornato. 

Ti consiglio di fare un if per controllare se il numero non va bene e nel caso stampare un messaggio di errore e uscire.

Se va bene prova ad estrarre l'ultima cifra. Che operazione serve?

**Comment by luca998** [comment]
il modulo?

**Comment by luca998** [comment]
in che senso il numero non va bene?

**Comment by FabioZTessitore** [comment]
il numero in input (ti ricordo che deve essere a 5 cifre)

**Comment by luca998** [comment]
L'if che ho fatto non fa bene il controllo?

**Comment by FabioZTessitore** [comment]
no perché scarta il 99999

però il consiglio è un altro. Invece di fare un if per controllare se va tutto bene, è meglio fare un if per controllare se va male e nel caso prendere provvedimenti (stampa messaggio ed esci).
In questo modo il codice seguente sarà più chiaro

**Comment by luca998** [comment]
Va bene

**Comment by FabioZTessitore** [comment]
devi aggiungermi come collaboratore

**Comment by luca998** [comment]
Non so perchè non mi funziona l'if per vedere se va male

**Comment by FabioZTessitore** [comment]
guarda le modifiche e vai avanti

**Comment by FabioZTessitore** [comment]
non sei autorizzato ad usare cicli

**Comment by FabioZTessitore** [comment]
ok, ci siamo quasi.
Puoi usare solo 10, niente 100, 1000 ecc

**Comment by FabioZTessitore** [comment]
va bene, andiamo avanti.
però non era necessario usare le variabili d1, d2, d3, d4
