### ISSUE TITLE
tabella

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/cifre#2]
prova a fare questa tabella. Puoi usare una sola variabile

![es2_31](https://cloud.githubusercontent.com/assets/3002194/20138978/fa2ea07e-a683-11e6-9c3a-2dfaa4bf5cdb.jpg)

**Comment by FabioZTessitore** [comment]
problemi?

**Comment by FabioZTessitore** [comment]
sei testardo
non puoi fare cicli

**Comment by luca998** [comment]
Ho corretto
